[package]
name = "git-stats"
version = "0.1.0"
authors = ["pkoerbitz"]
edition = "2018"

[dependencies]
git2 = "0.8"
docopt = "1"
serde = "1.0" # if you're using `derive(Deserialize)`
serde_derive = "1.0" # if you're using `derive(Deserialize)`